name:  Bug Report
description: Reportar un error o comportamiento inesperado
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un bug. Por favor completa la informaci贸n para ayudarnos a resolver el problema.

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del problema
      description: Describe claramente el bug que encontraste
      placeholder: Qu茅 pas贸 y qu茅 esperabas que pasara
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Pasos para reproducir
      description: Pasos detallados para reproducir el bug
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '...'
        3. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      description: Qu茅 esperabas que sucediera
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento actual
      description: Qu茅 est谩 sucediendo en su lugar
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Versi贸n
      description: Qu茅 versi贸n de ECB TOOL est谩s usando
      options:
        - 1.0.0 (latest)
        - Development branch
        - Otra (especificar en descripci贸n)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Sistema Operativo
      description: En qu茅 sistema operativo ocurre
      options:
        - Windows 11
        - Windows 10
        - Otro (especificar en descripci贸n)
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Versi贸n de Python
      description: Qu茅 versi贸n de Python est谩s usando
      options:
        - Python 3.13
        - Python 3.12
        - Python 3.11
        - Otra (especificar en descripci贸n)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Si hay logs de error, p茅galos aqu铆
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Capturas de pantalla
      description: Si aplica, a帽ade capturas de pantalla

  - type: textarea
    id: additional
    attributes:
      label: Informaci贸n adicional
      description: Cualquier otra informaci贸n relevante
